### ISSUE TITLE
maybe::operator>> の無用な `boost::none`

### ISSUE THREAD

**Issue by agate-pris** [LoliGothick/mitama-cpp-result#16]
`maybe<result_type>{boost::optional<result_type>{boost::none}}`

`boost::none` は不要

**Comment by agate-pris** [comment]
そもそもこの処理を包む `if constexpr` の分岐がそもそも不要である.

**Comment by LoliGothick** [comment]
I see,

**Comment by LoliGothick** [comment]
Merge
