### ISSUE TITLE
maybe<noncopyable_type> のテストの不足

### ISSUE THREAD

**Issue by agate-pris** [LoliGothick/mitama-cpp-result#23]
メンバ関数の呼び出しでエラーになる場合がある.

**Comment by agate-pris** [comment]
Boost.InPlaceがBoost.Optionalの中で壊れてるので `mitama::in_place` でなんとかするしか無いと主合われる

**Comment by LoliGothick** [comment]
Add test of `get_or_emplace` for noncopyable type in v7.1.0.
