### ISSUE TITLE
Unify if-statement style in `result.hpp`

### ISSUE THREAD

**Issue by ken-matsui** [LoliGothick/mitama-cpp-result#86]
This issue is related to #84.

To reply [your this comment](https://github.com/LoliGothick/mitama-cpp-result/pull/84#issuecomment-745141677), I totally agree with unifying with braces. Conversely, there are two styles with braces like the following:
```cpp
if ( cond )
   { ; }
else
   { ; }
```

vs

```cpp
if ( cond ) {
    ;
}
else {
    ;
}
```

Which style would you like to use?

**Comment by LoliGothick** [comment]
@ken-matsui  I prefer the first!
